### ISSUE TITLE
请教部署的问题

### ISSUE THREAD

**Issue by maicss** [echo9z/nuxt_blogs#1]
想请教的是Drone CI 打包部署时候的.env配置的问题。
**假设env文件里有敏感信息，不能写到仓库里。所以也不能写到pipeline里。** nuxt推荐使用.env配置变量。我看到你的项目里也是用了。请问你遇到了这个问题吗，如何处理的？

比如我的env里有四个变量，需要根据不同的环境来配置，假设只有两个环境，本地开发和线上，本地是两个数字，线上是三个数字：
```
a=11
b=22
c=33
d=44
```
目前我了解到的解决方案如下：
1. 先去drone ci的web端，在secret里添加一个条目，比如这里叫`build-env`
2. 在对应的value里填写上面的四个值：
```
a=111
b=222
c=333
d=444
```
3. 在pieline里添加以下代码：
```
# .drone.yml
kind: pipeline
name: default

steps:
- name: copy-env
  image: alpine:latest
  environment:
    BUILD_ENV:
      from_secret: build-env
  commands:
  - echo -n $BUILD_ENV > .env
- name: build
  image: node:18-alpine
  commands:
  - corepack enable && corepack prepare pnpm@latest --activate
  - pnpm -v
  - pnpm install
  - pnpm build
  - pnpm preview
```
这样每次得到的env文件好像是个空的，项目运行的时候，获取不到需要的env变量。
请问你能给一点意见或者建议吗？谢谢！
